# Personal
*Nationality*: British and Irish citizen. Born: Burnley, U.K.  
*www*: andrewbenito.github/AlphaBetEcon


# Profile

Chief European Economist at Eisler Capital. Previously, Managing Director at Goldman Sachs (8 years) and Research Manager at Bank of England (12 years, including secondments to the IMF and Banco de Espana). My work has been cited extensively by policy-makers and the media and been published in academic journals. I hold a PhD in Economics from the University of Warwick. I am also a Research Fellow at IZA, Institute of Labor Economics, Bonn.

# Employment 

**Chief European Economist** \hfill 2019 -   
*Eisler Capital*

**Managing Director, Chief UK Economist and Senior European Economist** \hfill 2011 - 2019  
*Goldman Sachs, Global Macro Research*

**Research Manager** \hfill 2008 - 11  
*Bank of England, Monetary Analysis*

**Visiting Scholar** \hfill 2006 -08  
*International Monetary Fund, Research Department (seconded from Bank of England)*

**Senior Economist** \hfill 2003 - 06  
*Bank of England, Monetary Analysis*

**Senior Economist** \hfill 2002 - 03  
*Banco de Espana, Research Department (seconded from Bank of England)*

**Economist** \hfill 1999 - 2002  
*Bank of England, Financial Stability*

**Leader, Modelling Team** \hfill 1997 - 99  
*Oxford Economic Research Associates*

# Education

**Ph.D. Economics** \hfill 1994 - 97  
*University of Warwick*

_Thesis_: Wage Premia in the British Labour Market  

**M.Sc. Economics** \hfill 1993 - 94   
*University of Warwick*

**B.Sc. Economics** \hfill 1990 - 93   
*Cardiff University*

# Journal Publications

Benito, A and Saleheen, J (2013), `Labour supply as a buffer: Evidence from UK households', *Economica* 80, 698-720 

Benito, A and Mumtaz, H (2009), `Excess sensitivity, liquidity constraints and the collateral role of housing', *Macroeconomic Dynamics*, 13, 305-326 

Benito, A (2009), `Who withdraws housing equity and why?', *Economica*, 76, 51-70 

Benito, A and Hernando, I (2008), `Labour demand, flexible contracts and financial factors', *Oxford Bulletin of Economics and Statistics*, 70, 283-301 

Benito, A and Hernando, I (2007), `Financial pressure and firm behaviour: Evidence from Spanish panel data', *Bulletin of Economic Research*, 59, 283-311 

Benito, A and Young, G (2007), `Financial pressure and balance sheet adjustment by firms',
*Oxford Bulletin of Economics and Statistics*, 69, 581-602.

Benito, A (2007), `The down-payment constraint and UK housing market: Does the theory fit the facts?', 
*Journal of Housing Economics*, 15, 1-20 

Benito, A (2006), `Does job insecurity affect household consumption?', *Oxford Economic Papers*, 56, 157-81 

Benito, A (2005), `Financial pressure, monetary policy effects and inventories: Firm-level evidence from a market-based and a bank-based financial system', *Economica*, 72, 201-224 

Benito, A and Young, G (2003), `Hard Times or Great Expectations? Dividend omissions and dividend cuts by UK firms', *Oxford Bulletin of Economics and Statistics*, 65, 531-57 

Benito, A (2000), `Inter-industry wage differentials in Great Britain', *Oxford Bulletin of Economics and Statistics*, 62, 727-746 

# Institutional Publications

Benito, A. and Young, G. (2021), `The UK productivity shortfall in an era of rising labour supply', *IZA Discussion Paper 14620* 

Benito, A. (2018), `Missing wage growth and ECB policy' , *European Views*, Goldman Sachs Research 

Benito, A. et al. (2017), `Drivers of UK asset prices - Since Brexit, politics matters more than economics', *European Economics Analyst*. Goldman Sachs Research

Benito, A. (2017), `How does monetary policy affect labor demand and labor productivity?', *IZA World of Labor*.

Benito, A. and Saleheen, J. (2012), `Labour supply as a buffer: Evidence from UK households',
*IZA Discussion Paper 6506* (Also, *Bank of England Working Paper No.426*). 

Benito, A. and Bunn, P. (2011), `Understanding labour force participation in the UK', *Bank of England Quarterly Bulletin*  

Benito, A. \textit{et al} (2010), `The effect of the financial crisis on supply', *Bank of England Quarterly Bulletin* 

Benito, A., \textit{et al} (2007),`The role of household debt and balance sheets in the monetary transmission mechanism', *Bank of England Quarterly Bulletin*

Benito, A. (2007), `What risks do housing markets pose for global growth?', *IMF World Economic Outlook*

Benito, A. (2007), `Housing market slowdowns', *IMF World Economic Outlook*

Benito, A., \textit{et al} (2006), `House prices and consumer spending', *Bank of England Quarterly Bulletin*

Benito, A. and Wood, R.(2005), `How important is housing market activity for durables spending?', *Bank of England Quarterly Bulletin* 

Benito, A. and Power, J. (2004), `Housing equity and consumption: insights from the Survey of English Housing', *Bank of England Quarterly Bulletin*, Autumn, 302-309. 

Benito, A. and Hernando, I. (2004), `Demanda de trabajo, contratos temporales y factores financieros', *Banco de Espana Boletin Economico* pp 71-74 

Benito, A., \textit{et al} (2001), `Analysing corporate and household sector balance sheets', *Bank of England Financial Stability Review*

Benito, A. and Vlieghe, G. (2000), `Stylised facts on UK corporate financial health: Evidence from micro-data', *Bank of England Financial Stability Review*.


# Awards

- IZA Research Fellow \hfill 2011-
- Special Session Award, *Money Macro Finance Conf.*, Cambridge \hfill 2003
- Human Capital and Mobility Fellowship, European Union \hfill 1995-97
- University Graduate Award}, University of Warwick \hfill 1993-94
- Sir Julian Hodge Award \hfill 1993
- Vauxhall Motors Award for Academic Excellence \hfill 1993

# Seminars

Banco de Espana, Bank of England, Banque de France, European Central Bank, European Economic Association, European University Institute, Goldman Sachs (London), Harvard University, International Monetary Fund, London School of Economics, Royal Economic Society Annual Conference, Society of Professional Economists, University of Cambridge, Universidad Carlos III Madrid, University of Oxford, University of Warwick.
